sudo: required
dist: trusty

env:
  - DOCKER_COMPOSE_VERSION="1.4.2"
  - DOCKER_COMPOSE_VERSION="1.5.2"
  - DOCKER_COMPOSE_VERSION="1.6.2"

cache:
  - apt

before_install:
  - sudo service memcached stop
  - sudo service docker stop
  - sudo apt-get update -qq && apt-get install apt-transport-https ca-certificates
  - printf "\n" | sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-cache policy docker-engine
  - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee -a /etc/apt/sources.list.d/docker.list
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes docker-engine
  - sudo service docker restart
  - docker --version
  - /usr/local/bin/docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - stty cols 160

script:
  - docker-compose up -d
  - docker-compose ps

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
