sudo: required
dist: trusty

env:
  - DOCKER_COMPOSE_VERSION="1.6.2"

cache:
  - apt

before_install:
  - sudo service memcached stop
  - sudo service docker stop
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --force-yes docker-engine
  - sudo service docker restart
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - stty cols 160

script:
  - docker-compose version
  - docker-compose -p up -d
  - sleep 3
  - docker-compose -p phalcon ps
  - docker exec -ti phalcon_php_5.6_fpm php --ri phalcon

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
