# MySQL
db:
  restart: always
  image: mysql:latest
  container_name: mysql_db
  expose:
    - "3306"
  ports:
    - "3307:3306"
  volumes:
    - ./conf/mysql:/etc/mysql/conf.d
  environment:
    MYSQL_DATABASE: phalcondb
    MYSQL_USER: phalcon
    MYSQL_PASSWORD: secret
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

# Beanstalkd
queue:
  restart: always
  image: klay/beanstalkd
  container_name: beanstalkd_queue
  ports:
    - "11300:11300"

# PHP FPM
php:
  restart: always
  image: klay/php-fpm
  container_name: php56_app
  ports:
    - "9000:9000"
    - "10000:10000"
  volumes:
    - ./conf/php-fpm:/etc/php-fpm.d
    - ./logs/php-fpm:/var/log/php-fpm
    - ./http:/srv/http

# Nginx
nginx:
  restart: always
  image: klay/nginx
  container_name: nginx_web
  ports:
    - "80:80"
  volumes:
    - ./certs/nginx:/etc/nginx/certs
    - ./conf/nginx:/etc/nginx/conf.d
    - ./vhost:/etc/nginx/sites-enabled
    - ./http:/srv/http
  environment:
    # production | development | staging | testing
    APP_ENV: development

  links:
    - db
    - queue
    - php