db:
  image: mysql:latest
  container_name: mysql_db
  expose:
    - "3306"
  ports:
    - "3307:3306"
  volumes:
    - ./conf/mysql:/etc/mysql/conf.d
  environment:
    MYSQL_DATABASE: phalcondb
    MYSQL_USER: phalcon
    MYSQL_PASSWORD: secret
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
app:
  image: klay/php-fpm
  container_name: php_app
  tty: true
  ports:
    - "9000:9000"
    - "10000:10000"
  volumes:
    - ./logs/php-fpm:/var/log/php-fpm
web:
  tty: true
  image: klay/nginx
  container_name: nginx_web
  ports:
    - "80:80"
  volumes:
    - ./certs/nginx:/etc/nginx/certs
    - ./conf/nginx:/etc/nginx/conf.d
    - ./vhost:/etc/nginx/sites-enabled
    - ./logs/nginx:/var/log/nginx
    - ./http:/srv/http
  links:
    - app
