version: '2'

services:
  application:
    build: containers/core
    container_name: phalcon.compose.volume
    volumes:
      - ./application:/project
      - ./cache:/project/cache
      - ./logs:/project/logs
    tty: true

  mongo:
    restart: always
    image: mongo:3.2
    container_name: phalcon.compose.mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  postgres:
    restart: always
    image: postgres:9.5
    container_name: phalcon.compose.postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - variables.env

  mysql:
    restart: always
    image: mysql:5.7
    container_name: phalcon.compose.mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    env_file:
          - variables.env

  memcached:
    restart: always
    image: memcached:1.4
    container_name: phalcon.compose.memcached
    ports:
      - "11211:11211"

  queue:
    restart: always
    image: phalconphp/beanstalkd:1.10
    container_name: phalcon.compose.beanstalkd
    ports:
      - "11300:11300"
    volumes:
      - beanstalk:/data

  aerospike:
    restart: always
    image: aerospike
    container_name: phalcon.compose.aerospike
    expose:
      - "3000"
      - "3001"
      - "3002"
      - "3003"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
        - aerospike:/opt/aerospike/data
        - ./conf/aerospike/aerospike.conf:/etc/aerospike/aerospike.conf

  redis:
    restart: always
    image: redis:latest
    container_name: phalcon.compose.redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  php:
    image: phalconphp/php-apache:ubuntu-16.04
    restart: always
    container_name: phalcon.compose.php
    working_dir: /project
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    volumes_from:
      - application
    depends_on:
      - mysql
      - queue
      - redis
      - memcached
    env_file:
      - variables.env

  ssh:
    image: jeroenpeeters/docker-ssh
    restart: always
    container_name: phalcon.compose.ssh
    depends_on:
      - php
    ports:
      - "2222:22"
      - "8022:8022"
    env_file:
          - variables.env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mongo:
    driver: local
  postgres:
    driver: local
  mysql:
    driver: local
  beanstalk:
    driver: local
  redis:
    driver: local
  aerospike:
    driver: local
