version: '2'

services:
  application:
    build: containers/core
    container_name: phalcon.compose.volume
    volumes:
      - ./application:/var/www/phalcon
      - ./cache:/var/cache/phalcon
      - ./logs:/var/log/phalcon
    tty: true

  mongo:
    restart: always
    image: mongo:3.2
    container_name: phalcon.compose.mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  postgres:
    restart: always
    image: postgres:9.5
    container_name: phalcon.compose.postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ''
      PGDATA: /var/lib/postgresql/data/pgdata

  mysql:
    restart: always
    image: mysql:5.7
    container_name: phalcon.compose.mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: phalcondb
      MYSQL_USER: phalcon
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  memcached:
    restart: always
    image: memcached:1.4
    container_name: phalcon.compose.memcached
    ports:
      - "11211:11211"

  queue:
    restart: always
    image: phalconphp/beanstalkd:1.10
    container_name: phalcon.compose.beanstalkd
    ports:
      - "11300:11300"
    volumes:
      - beanstalk:/data

  aerospike:
    restart: always
    image: aerospike
    container_name: phalcon.compose.aerospike
    expose:
      - "3000"
      - "3001"
      - "3002"
      - "3003"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
        - ./conf/aerospike/aerospike.conf:/etc/aerospike/aerospike.conf

  redis:
    restart: always
    image: redis:latest
    container_name: phalcon.compose.redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  php:
    image: phalconphp/php-fpm:5.6
    restart: always
    container_name: phalcon.compose.php
    expose:
      - "9000"
      - "10000"
    ports:
      - "9000:9000"
      - "10000:10000"
    volumes_from:
      - application
    depends_on:
      - mysql
      - queue
      - redis
      - memcached

  nginx:
    restart: always
    image: phalconphp/nginx:latest
    container_name: phalcon.compose.nginx
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        - php
    volumes:
      - ./conf/nginx/certs:/etc/nginx/certs
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/vhost:/etc/nginx/sites-enabled
    volumes_from:
      - application
    environment:
      # production | development | staging | testing
      APPLICATION_ENV: development

volumes:
  mongo:
    driver: local
  postgres:
    driver: local
  mysql:
    driver: local
  beanstalk:
    driver: local
  redis:
    driver: local
